Repository tlsfuzzer/python-ecdsa, pull requests merged in 2019-10, with the labels that each got.

#118 Support for X9.62 formatted public keys
  src/ecdsa/keys.py
  src/ecdsa/numbertheory.py
  src/ecdsa/test_pyecdsa.py
Labels: feature

#123 add MalformedPointError to __all__
  src/ecdsa/keys.py
Labels: bug

#124 Backport signature decode
  .coveragerc
  .travis.yml
  README.md
  build-requirements-2.6.txt
  build-requirements-3.2.txt
  build-requirements-3.3.txt
  build-requirements.txt
  ecdsa/__init__.py
  ecdsa/der.py
  ecdsa/keys.py
  ecdsa/test_der.py
  ecdsa/test_malformed_sigs.py
  ecdsa/test_pyecdsa.py
  ecdsa/util.py
  tox.ini
Labels: bug

#132 document exceptions in from_* methods
  README.md
Labels: maintenance

#134 uplift NEWS from 0.13 branch
  NEWS
Labels: maintenance

#125 Apply nonce bit-length mitigation to stop timing leakage.
  src/ecdsa/curves.py
  src/ecdsa/ecdsa.py
  src/ecdsa/ellipticcurve.py
  src/ecdsa/rfc6979.py
  src/ecdsa/util.py
Labels: feature

#126 More test coverage
  .coveragerc
  README.md
  src/ecdsa/__init__.py
  src/ecdsa/keys.py
  src/ecdsa/numbertheory.py
  src/ecdsa/test_pyecdsa.py
Labels: maintenance

#137 make pypy and pypy3 support official
  .travis.yml
  README.md
Labels: maintenance

#139 don't allow for creation of malformed DER files
  src/ecdsa/keys.py
  src/ecdsa/test_pyecdsa.py
Labels: bug

#138 Correct handling of BIT STRING in DER
  src/ecdsa/der.py
  src/ecdsa/keys.py
  src/ecdsa/test_der.py
  src/ecdsa/test_pyecdsa.py
Labels: bug

#117 Provide documentation for VerifyingKey and SigningKey
  src/ecdsa/keys.py
  src/ecdsa/util.py
Labels: maintenance

#142 add python3.8 to tests, enable nightly
  .travis.yml
  setup.py
  tox.ini
Labels: maintenance

#141 Add condition coverage
  .travis.yml
  README.md
  diff-instrumental.py
Labels: maintenance

#143 Bytes-like object support
  .travis.yml
  src/ecdsa/_compat.py
  src/ecdsa/der.py
  src/ecdsa/keys.py
  src/ecdsa/rfc6979.py
  src/ecdsa/test_der.py
  src/ecdsa/test_keys.py
  src/ecdsa/util.py
Labels: bug, maintenance

#145 testing with hypothesis
  .gitignore
  .travis.yml
  build-requirements-2.6.txt
  build-requirements-3.3.txt
  build-requirements.txt
  src/ecdsa/curves.py
  src/ecdsa/der.py
  src/ecdsa/keys.py
  src/ecdsa/test_malformed_sigs.py
  tox.ini
Labels: maintenance

#150 fix st_fuzzed_sig
  src/ecdsa/test_malformed_sigs.py
Labels: maintenance
