Repository tlsfuzzer/python-ecdsa, pull requests merged in 2019-11, with the labels that each got.

#154 Use math.gcd if available
  src/ecdsa/numbertheory.py
Labels: maintenance

#147 Minor speed-up
  README.md
  src/ecdsa/keys.py
  src/ecdsa/numbertheory.py
  src/ecdsa/test_numbertheory.py
Labels: maintenance

#151 Ellipticcurve tests
  src/ecdsa/test_ellipticcurve.py
Labels: maintenance

#153 Little more test coverage
  src/ecdsa/test_malformed_sigs.py
  src/ecdsa/test_numbertheory.py
Labels: maintenance

#61 Added support for Brainpool r1
  speed.py
  src/ecdsa/__init__.py
  src/ecdsa/curves.py
  src/ecdsa/ecdsa.py
  src/ecdsa/test_pyecdsa.py
Labels: feature

#157 der: fix encoding and decoding OIDs
  src/ecdsa/der.py
  src/ecdsa/test_der.py
  src/ecdsa/test_malformed_sigs.py
  src/ecdsa/test_pyecdsa.py
Labels: bug

#158 add 0.14 changes to NEWS
  .gitattributes
  MANIFEST.in
  NEWS
  src/ecdsa/_version.py
Labels: maintenance

#161 Added __eq__ method to classes to improve comparison abilities
  .gitignore
  src/ecdsa/ecdsa.py
  src/ecdsa/ellipticcurve.py
  src/ecdsa/keys.py
  src/ecdsa/test_ecdsa.py
  src/ecdsa/test_ellipticcurve.py
  src/ecdsa/test_keys.py
Labels: feature

#149 add ecdh class
  README.md
  src/ecdsa/__init__.py
  src/ecdsa/ecdh.py
  src/ecdsa/test_ecdh.py
Labels: feature

#164 also include speed of ECDH in speed.py
  speed.py
Labels: feature

#165 six: expect specific version
  .travis.yml
  setup.py
  tox.ini
Labels: maintenance

#169 Bitwise randrange
  src/ecdsa/util.py
Labels: maintenance
