Repository tlsfuzzer/python-ecdsa, pull requests merged in 2020-11, with the labels that each got.

#212 add option to lazily precompute multiplication tables
  .gitignore
  src/ecdsa/ellipticcurve.py
  tox.ini
Labels: feature

#215 fix truncation of hash input with order bit size not multiple of 8
  src/ecdsa/keys.py
Labels: bug

#216 Fix docstring in keys.py: RFC6697 should be RFC6979
  src/ecdsa/keys.py
Labels: maintenance

#217 Exclude version specific coverage
  src/ecdsa/_compat.py
  src/ecdsa/der.py
  src/ecdsa/test_ecdh.py
  src/ecdsa/util.py
  tox.ini
Labels: maintenance

#218 refresh readme contents
  README.md
Labels: maintenance

#219 Speed up single-shot verify
  README.md
  speed.py
  src/ecdsa/ellipticcurve.py
  src/ecdsa/test_jacobi.py
  tox.ini
Labels: feature
